# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    # gobinary: "go1.16"
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: linux
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - 
    tap:
      owner: eezhee
      name: homebrew-eezhee
    description: "The easiest and fastest way to create a kubernutes cluster on a variety of clouds"    
    license: "Apache 2.0"
    homepage: "https://github.com/eezhee/eezhee"
    skip_upload: false